Parameters:
  bucketName:
    Type: String
    Default: "mys3bucket"
    Description: "Enter Your S3 Bucket"

  vpcCIDR:
    Type: String
    Default: "XXX.XXX.0.0/16"
    Description: "Enter Your VPC CIDR"

  policyName:
    Type: String
    Default: "leopolicy"
    Description: Enter your Policy Name
  
  MyEC2LaunchTemplate:
    Type: String
    Default: "leolaunchtemplate"
    Description: Enter your launch templatename
  

  
  subnet1CIDR:
    Type: String
    Default: "XXX.XXX.1.0/24"
    Description: "Enter Your Subnet1 CIDR"
  
  subnet2CIDR:
    Type: String
    Default: "XXX.XXX.2.0/24"
    Description: "Enter Your Subnet2 CIDR"

  subnet3CIDR:
    Type: String
    Default: "XXX.XXX.3.0/24"
    Description: "Enter Your Subnet3 CIDR"

  subnet4CIDR:
    Type: String
    Default: "XXX.XXX.4.0/24"
    Description: "Enter Your Subnet4 CIDR"

  az1:
    Type: String
    Description: "Enter Your AZ-1 ID"

  az2:
    Type: String
    Description: "Enter Your AZ-2 ID"

  dbPort:
    Type: Number
    Default: 3306
    Description: "Enter Your Database Port Number"

  amiID:
    Type: String
    Default: 'ami-0bb84b8ffd87024d8'
    Description: "Enter Your EC2 AMI ID"
  
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
      - t3.micro
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
  
  EC2KeyPair:
    Type: AWS::EC2::KeyPair::KeyName

  DBInstanceID:
    Type: String
    Description: "Enter Your RDS Instance Name"
  
  DBName:
    Type: String
    Description: "Enter Your RDS DB Name"

  Targetgroupname:
    Type: String
    Default: "leotg"
    Description: "Enter your target groupe name"

  Myapplbname:
    Type: String
    Default: 'Myapplb'
    Description: "Enter Your application load balancer name"

  AutoScalingGroup:
    Type: String
    Default: 'my-autoscalinggroup'
    Description: "Enter Your autoscaling group name"


  
  DBInstanceClass:
    Type: String
    Default: db.t3.micro
    Description: "Enter Your RDS Instance Class"
  
  DBAllocatedStorage:
    Default: '20'
    Description: The size of the database (GiB)
    Type: Number
    MinValue: '20'
    MaxValue: '65536'
    ConstraintDescription: must be between 20 and 65536 GiB.
  
  DBEngine:
    Type: String
    Default: 'MySQL'
    Description: Enter Your RDS DB Engine Type
  
  EngineVersion:
    Type: String
    Default: '8.0.33'
    Description: Enter Your RDS DB Engine Version
  
  DBUsername:
    NoEcho: 'true'
    Description: Username for MySQL database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Description: Password MySQL database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.


Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref bucketName
      VersioningConfiguration:
        Status: Enabled

  customVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref vpcCIDR
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        - Key: stack
          Value: production

  customInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: stack
        Value: production
  
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref customVPC
      InternetGatewayId:
        Ref: customInternetGateway

  publicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: customVPC
      Tags:
      - Key: stack
        Value: production
  
  publicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId:
        Ref: publicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: customInternetGateway
  
  publicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: customVPC
      CidrBlock: !Ref subnet1CIDR
      AvailabilityZone: !Ref az1
      MapPublicIpOnLaunch: true
      Tags:
      - Key: stack
        Value: production

  publicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: customVPC
      CidrBlock: !Ref subnet2CIDR
      AvailabilityZone: !Ref az2
      MapPublicIpOnLaunch: true
      Tags:
      - Key: stack
        Value: production

  privateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: customVPC
      CidrBlock: !Ref subnet3CIDR
      AvailabilityZone: !Ref az1
      Tags:
      - Key: stack
        Value: production

  privateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: customVPC
      CidrBlock: !Ref subnet4CIDR
      AvailabilityZone: !Ref az2
      Tags:
      - Key: stack
        Value: production
  
  publicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: publicSubnet1
      RouteTableId:
        Ref: publicRouteTable

  publicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: publicSubnet2
      RouteTableId:
        Ref: publicRouteTable

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: !Ref customVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0

  albSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: !Ref customVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow DB Connection to RDS
      VpcId: !Ref customVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref dbPort
          ToPort: !Ref dbPort
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0

  MyEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref amiID
      KeyName: !Ref EC2KeyPair
      InstanceType: !Ref InstanceTypeParameter
      SecurityGroupIds: 
        - !Ref InstanceSecurityGroup
      SubnetId: !Ref publicSubnet1

  MyEC2Instance1: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref amiID
      KeyName: !Ref EC2KeyPair
      InstanceType: !Ref InstanceTypeParameter
      SecurityGroupIds: 
        - !Ref InstanceSecurityGroup
      SubnetId: !Ref publicSubnet2



  firstIAMPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Ref policyName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'cloudformation:Describe*'
              - 'cloudformation:List*'
              - 'cloudformation:Get*'
            Resource: '*'
          - Effect: Allow
            Action:
              - 's3:*'
            Resource: '*'
                                             

  RootRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - !Ref firstIAMPolicy
        - arn:aws:iam::aws:policy/AmazonSageMakerReadOnly
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

  DBSubnetGroup: 
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: CustomSubnetGroup
      SubnetIds: 
        - !Ref privateSubnet1
        - !Ref privateSubnet2


  


  MyLaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: !Ref MyEC2LaunchTemplate
      LaunchTemplateData:
        ImageId: !Ref amiID
        InstanceType: !Ref InstanceTypeParameter
        KeyName: !Ref EC2KeyPair
        SecurityGroupIds:
          - !Ref InstanceSecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            echo "Hello World" > /var/tmp/hello.txt
      TagSpecifications:
        - ResourceType: launch-template
          Tags:
            - Key: Name
              Value: MyEC2Instance2


  MyAutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      MinSize: '2'
      MaxSize: '3'
      DesiredCapacity: '2'
      LaunchTemplate:
        LaunchTemplateId: !Ref MyLaunchTemplate
        Version: !GetAtt MyLaunchTemplate.LatestVersionNumber
      VPCZoneIdentifier:
        - !Ref publicSubnet1
        - !Ref publicSubnet2
      Tags:
        - Key: Name
          Value: MyInstance
          PropagateAtLaunch: true


  


  MyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Ref Targetgroupname
      Protocol: HTTP
      Port: 80
      VpcId: !Ref customVPC
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckPort: traffic-port
      HealthCheckProtocol: HTTP
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      TargetType: instance
      Targets:
        - Id: !Ref MyEC2Instance
          Port: 80


  MyApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref Myapplbname
      IpAddressType: ipv4
      SecurityGroups: 
        - !Ref albSecurityGroup
      Subnets:
        - !Ref publicSubnet1
        - !Ref  publicSubnet2
      Scheme: internet-facing
      Type: application

  MyALBListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MyTargetGroup
      LoadBalancerArn: !Ref MyApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
    
  
  rdsDBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceID
      DBName: !Ref DBName
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      Engine: !Ref DBEngine
      EngineVersion: "8.0.33"
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups: 
        - !Ref RDSSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
